spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      username: adam
      password: password
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.adam.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.adam.ecommerce.kafka.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: adam
    password: password
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connection timeout: 5000
        timeout: 3000
        write timeout: 5000
server:
  port: 8040