### Create a new order
POST http://localhost:8222/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "reference": "string",
  "amount": 10,
  "paymentMethod": "PAYPAL",
  "customerId": "5",
  "products": [
    {
      "productId": 1201,
      "quantity": 1
    }
  ]
}
