server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DB}?retryWrites=true&w=majority&appName=ecommerce

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/





